version: '3.8'

name: express-api-demo

services:
  db:
    image: postgres:17-alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=express-api-demo
      - POSTGRES_USER=express-api-demo
      - POSTGRES_PASSWORD=express-api-demo
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
